version: "2"

services:
  mongo:
    image: scrapyg/patdoc-db
    build:
      context: ./db
    restart: always
    volumes:
      - ./db/data:/data/db
    ports:
      - 3001:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/patdoc --quiet
      interval: 30s
      timeout: 15s
      retries: 2
      start_period: 15s

  api:
    image: scrapyg/patdoc-api
    build:
      context: ./api
    ports:
      - 3000:3000
    restart: "always"
    depends_on:
      mongo:
        condition: service_healthy

  client:
    image: scrapyg/patdoc-client
    build:
      context: ./client
    ports:
      - 8080:80
